# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  hash_tbl_test_config = debug
endif
ifeq ($(config),release)
  hash_tbl_test_config = release
endif

PROJECTS := hash_tbl_test

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

hash_tbl_test:
ifneq (,$(hash_tbl_test_config))
	@echo "==== Building hash_tbl_test ($(hash_tbl_test_config)) ===="
	@${MAKE} --no-print-directory -C . -f hash_tbl_test.make config=$(hash_tbl_test_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f hash_tbl_test.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   hash_tbl_test"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"